spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/articletest
#    url: jdbc:h2:~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true #???? 8?
      format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
